### ISSUE TITLE
Run PE

### ISSUE THREAD

**Issue by im-code** [CasualX/pelite#10]
Hi! Can I run PE file from memory using this package, not just to find information? Thank you!

**Comment by CasualX** [comment]
Right now the answer is: sort of... and you'd have to implement it yourself.

The long answer is that it's tricky due to Rust's strict memory aliasing rules, I'm using shared borrows all over the place to reference parts of the PE file exposed through that specific object's API. However that means you can't at the same time modify that memory (even though it may be disjoint, Rust just sees a `&[u8]` spanning the whole image.

While I would like an API for setting up the PE for running from memory, due to the above considerations it is not implemented as I don't really know of a clean way to implement it in Rust.

So if you don't mind just hacking it, the proper way would be to copy the necessary information (imports, relocations, TLS) and then act on them after you've released all borrows you used to gather this information and implement it yourself.

**Comment by CasualX** [comment]
It turned out I was mistaken and it's fairly trivial to extend the functionality to manually map a DLL, see #12 

It's heavy WIP but it may help you: right now it can only load DLLs in your own process (no manual map dll injection) and TLS is blargh. But it should work.

**Comment by CasualX** [comment]
I'll close this in favor of just tracking the pull request
