### ISSUE TITLE
Add macro support for WideStr

### ISSUE THREAD

**Issue by not-wlan** [CasualX/pelite#191]
Adding a proc macro for WideStr would allow having WideStr constants. 

```rs
#[proc_macro]
pub fn wstringify(item: TokenStream) -> TokenStream {
    let item = syn::parse_macro_input!(item as LitStr);
    let value: String = item.value();
    let mut chars: Vec<u16> = value.encode_utf16().collect();
    chars.insert(0, u16::try_from(chars.len()).unwrap());
    let result = quote!{[#(#chars),*]};
    TokenStream::from(result)
}
// 
pub const ABC : [u16; 4] /* WideStr */ = wstringify!("ABC");
```
*Uses [quote](https://docs.rs/quote/0.6.12/quote/) and [syn](https://docs.rs/syn/0.15.36/syn/)*

This would also require WideStr to be sized though.

**Comment by CasualX** [comment]
Hmm I've written widestr macros before (see [obfstr](https://github.com/CasualX/obfstr)) perhaps it is fine to copy&paste its implementation here as well instead of requiring another dependency?

Further there's a small problem in interpretation: there are several ways widestrings are defined. Do you want classic C-like nul-terminated widestrings? Do you want word prefixed widestrings as used by names of resources? Do you want Rust-like strings and use pointer + length, allowing nul bytes in the string itself?

I've struggled with this and considered just going with Rust-like strings (since all nul-terminated and length word prefixed variants can be expressed with pointer+length) however passing these strings to WinAPI methods that want some variant then still require allocation...

That said in practice I've never actually needed the length-word prefixed version so I might just go ahead and do this.

Unfortunately `proc_macro` isn't stable yet but that's easily worked around and I'm not a fan of quote and syn purely because they are massive required dependencies which make everything slow as they need to be compiled before anything (eg. cargo check) can be done. This is simple enough to do myself though.

**Comment by not-wlan** [comment]
> Unfortunately proc_macro isn't stable yet 
I thought it was stable by now?
I agree syn and quote are rather heavy for this task, I had them installed for another macro already.

My main issue at the moment being that I have two constants that I have to convert to WideStr in order to interact with the resources API. Having literals here would not only clean up the source code but also make it more readable.

**Comment by CasualX** [comment]
Fair enough, so I'll just change the API to expose `&[u16]` directly and add a macro to convert string literals to `&[u16]`.

There's also the alternative of adding a `&str` variant to `Name` to allow you to provide your own utf8 strings and the code is clever enough to know how to compare these names.

**Comment by not-wlan** [comment]
Either should be fine

**Comment by CasualX** [comment]
Hey @not-wlan can you check if this would solve your problem? `Name` instances now allow plain Rust strings so they are usable with APIs taking `Name` arguments.
